"""uid table add image

Revision ID: 2b8d6396368d
Revises: e29177ffd807
Create Date: 2020-02-12 14:29:41.480086

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2b8d6396368d'
down_revision = 'e29177ffd807'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('UID', sa.Column('image', sa.String(length=65535), nullable=True))
    op.create_index(op.f('ix_UID_image'), 'UID', ['image'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_UID_image'), table_name='UID')
    op.drop_column('UID', 'image')
    # ### end Alembic commands ###
