"""post table add image

Revision ID: 2d29d50a875b
Revises: 2b8d6396368d
Create Date: 2020-02-12 14:39:00.905101

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2d29d50a875b'
down_revision = '2b8d6396368d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('image', sa.String(length=65535), nullable=True))
    op.create_index(op.f('ix_post_image'), 'post', ['image'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_post_image'), table_name='post')
    op.drop_column('post', 'image')
    # ### end Alembic commands ###
