"""uid table

Revision ID: e29177ffd807
Revises: ae346256b650
Create Date: 2020-02-12 09:47:41.686382

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e29177ffd807'
down_revision = 'ae346256b650'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('UID',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uid', sa.String(length=64), nullable=True),
    sa.Column('door', sa.String(length=64), nullable=True),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('code', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_UID_code'), 'UID', ['code'], unique=False)
    op.create_index(op.f('ix_UID_door'), 'UID', ['door'], unique=False)
    op.create_index(op.f('ix_UID_name'), 'UID', ['name'], unique=False)
    op.create_index(op.f('ix_UID_uid'), 'UID', ['uid'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_UID_uid'), table_name='UID')
    op.drop_index(op.f('ix_UID_name'), table_name='UID')
    op.drop_index(op.f('ix_UID_door'), table_name='UID')
    op.drop_index(op.f('ix_UID_code'), table_name='UID')
    op.drop_table('UID')
    # ### end Alembic commands ###
