"""uid table

Revision ID: fd1951bf5645
Revises: 780739b227a7
Create Date: 2020-02-11 16:38:51.041259

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fd1951bf5645'
down_revision = '780739b227a7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('UID',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uid', sa.String(length=64), nullable=True),
    sa.Column('door', sa.String(length=64), nullable=True),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('code', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_UID_code'), 'UID', ['code'], unique=False)
    op.create_index(op.f('ix_UID_door'), 'UID', ['door'], unique=False)
    op.create_index(op.f('ix_UID_name'), 'UID', ['name'], unique=False)
    op.create_index(op.f('ix_UID_uid'), 'UID', ['uid'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_UID_uid'), table_name='UID')
    op.drop_index(op.f('ix_UID_name'), table_name='UID')
    op.drop_index(op.f('ix_UID_door'), table_name='UID')
    op.drop_index(op.f('ix_UID_code'), table_name='UID')
    op.drop_table('UID')
    # ### end Alembic commands ###
